import { spawn, type ChildProcess } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { config, hasCredentials } from "../config.js";

/** GO2RTC_BIN from .env wins; otherwise use the binary bundled by go2rtc-static. */
function resolveGo2rtcBin(): string {
  if (config.go2rtc.bin !== "" && config.go2rtc.bin !== "auto") return config.go2rtc.bin;
  // go2rtc-static echoes process.env.GO2RTC_BIN verbatim, so our "auto"
  // sentinel must not be visible to it when we want the bundled binary.
  if (process.env.GO2RTC_BIN === "auto") delete process.env.GO2RTC_BIN;
  const require = createRequire(import.meta.url);
  return require("go2rtc-static") as string;
}

/**
 * Generates the go2rtc config from .env and supervises the go2rtc process.
 * The generated YAML contains RTSP credentials, so it lives in the
 * git-ignored .runtime/ directory and the API listens on 127.0.0.1 only.
 */

export function streamName(channel: number, subtype: 0 | 1): string {
  return subtype === 0 ? `cam${channel}_main` : `cam${channel}_sub`;
}

function buildYaml(): string {
  const { host, rtspPort, user, pass, channels } = config.dvr;
  const lines: string[] = [
    "# GENERATED by apps/server — do not edit; contains credentials.",
    "streams:",
  ];
  for (let ch = 1; ch <= channels; ch++) {
    for (const subtype of [0, 1] as const) {
      const url = `rtsp://${encodeURIComponent(user)}:${encodeURIComponent(pass)}@${host}:${rtspPort}/cam/realmonitor?channel=${ch}&subtype=${subtype}`;
      lines.push(`  ${streamName(ch, subtype)}: "${url}#backchannel=0"`);
    }
  }
  lines.push(
    "api:",
    `  listen: "127.0.0.1:${config.go2rtc.apiPort}"`,
    "rtsp:",
    '  listen: ""',
    "webrtc:",
    `  listen: ":${config.go2rtc.webrtcPort}"`,
    "  candidates:",
    "    - stun:8555",
    "log:",
    "  level: info",
  );
  return lines.join("\n") + "\n";
}

let child: ChildProcess | undefined;
let stopped = false;

export function startGo2rtc(log: (msg: string) => void): void {
  if (!hasCredentials) {
    log("go2rtc not started: DVR credentials missing in .env");
    return;
  }
  mkdirSync(config.runtimeDir, { recursive: true });
  const configPath = path.join(config.runtimeDir, "go2rtc.yaml");
  writeFileSync(configPath, buildYaml(), { mode: 0o600 });

  let bin: string;
  try {
    bin = resolveGo2rtcBin();
  } catch (err) {
    log(`go2rtc binary not found: ${(err as Error).message}`);
    return;
  }

  const launch = (): void => {
    if (stopped) return;
    child = spawn(bin, ["-config", configPath], { stdio: ["ignore", "pipe", "pipe"] });
    child.stdout?.on("data", (d: Buffer) => log(`[go2rtc] ${d.toString().trimEnd()}`));
    child.stderr?.on("data", (d: Buffer) => log(`[go2rtc] ${d.toString().trimEnd()}`));
    child.on("error", (err) => {
      log(`go2rtc failed to start: ${err.message} (set GO2RTC_BIN in .env or reinstall deps for go2rtc-static)`);
    });
    child.on("exit", (code) => {
      if (stopped) return;
      log(`go2rtc exited with code ${code ?? "?"}, restarting in 3s`);
      setTimeout(launch, 3000);
    });
  };
  launch();
}

export function stopGo2rtc(): void {
  stopped = true;
  child?.kill("SIGTERM");
}

/** True once the go2rtc API answers. */
export async function go2rtcAlive(): Promise<boolean> {
  try {
    const res = await fetch(`${config.go2rtc.apiBase}/api`, { signal: AbortSignal.timeout(1500) });
    return res.ok;
  } catch {
    return false;
  }
}

export interface StreamState {
  online: boolean;
}

/** Producer state per stream from the go2rtc API. */
export async function getStreamStates(): Promise<Record<string, StreamState>> {
  const res = await fetch(`${config.go2rtc.apiBase}/api/streams`, {
    signal: AbortSignal.timeout(3000),
  });
  if (!res.ok) throw new Error(`go2rtc /api/streams → ${res.status}`);
  const body = (await res.json()) as Record<string, unknown>;
  const out: Record<string, StreamState> = {};
  for (const name of Object.keys(body)) out[name] = { online: true };
  return out;
}

/** WHEP-style SDP exchange, proxied so the go2rtc API stays private. */
export async function webrtcOffer(src: string, offerSdp: string): Promise<string> {
  const res = await fetch(
    `${config.go2rtc.apiBase}/api/webrtc?src=${encodeURIComponent(src)}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/sdp" },
      body: offerSdp,
      signal: AbortSignal.timeout(10000),
    },
  );
  if (!res.ok) throw new Error(`go2rtc webrtc offer for ${src} → ${res.status}`);
  return res.text();
}
